name = "SHP Headless PWA"
handle = "shopify-headless-pwa"
client_id = "cec3787d1e417ec63c8220a3aa8f7a6a"

[build]
automatically_update_urls_on_dev = true

[access_scopes]
# Storefront is separate; these are Admin scopes.
scopes = "read_products,write_customers,read_orders"

[auth]
redirect_urls = [
  "https://localhost:3000/auth/callback",
  "https://your-production-domain.com/auth/callback"
]

[webhooks]
api_version = "2025-10"

[storefront]
storefront_access_token = "a20a3b321f8f4ffa3e358acbc25b7cde"
api_version = "2025-10"